<?xml version="1.0" encoding="utf-8"?><Database Name="QLBANSACH" Class="QLBanSachDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=NTKHAI1996-PC\SQL2012;Initial Catalog=QLBANSACH;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLBANSACHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIETSACH" Member="VIETSACHes">
    <Type Name="VIETSACH">
      <Column Name="MaTG" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Masach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Vaitro" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Vitri" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TACGIA_VIETSACH" Member="TACGIA" ThisKey="MaTG" OtherKey="MaTG" Type="TACGIA" IsForeignKey="true" />
      <Association Name="SACH_VIETSACH" Member="SACH" ThisKey="Masach" OtherKey="Masach" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetRoles" Member="AspNetRoles">
    <Type Name="AspNetRole">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="RoleId" Type="AspNetUserRole" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserRoles" Member="AspNetUserRoles">
    <Type Name="AspNetUserRole">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetRole" ThisKey="RoleId" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUser">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="UserId" Type="AspNetUserRole" />
      <Association Name="AspNetUser_DONDATHANG" Member="DONDATHANGs" ThisKey="Id" OtherKey="Id" Type="DONDATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETDONTHANG" Member="CHITIETDONTHANGs">
    <Type Name="CHITIETDONTHANG">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Masach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dongia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="DONDATHANG_CHITIETDONTHANG" Member="DONDATHANG" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="DONDATHANG" IsForeignKey="true" />
      <Association Name="SACH_CHITIETDONTHANG" Member="SACH" ThisKey="Masach" OtherKey="Masach" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHUDE" Member="CHUDEs">
    <Type Name="CHUDE">
      <Column Name="MaCD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="CHUDE_SACH" Member="SACHes" ThisKey="MaCD" OtherKey="MaCD" Type="SACH" />
    </Type>
  </Table>
  <Table Name="dbo.DONDATHANG" Member="DONDATHANGs">
    <Type Name="DONDATHANG">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Dathanhtoan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Tinhtranggiaohang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Ngaydat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ngaygiao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="DONDATHANG_CHITIETDONTHANG" Member="CHITIETDONTHANGs" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="CHITIETDONTHANG" />
      <Association Name="AspNetUser_DONDATHANG" Member="AspNetUser" ThisKey="Id" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHAXUATBAN" Member="NHAXUATBANs">
    <Type Name="NHAXUATBAN">
      <Column Name="MaNXB" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNXB" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="NHAXUATBAN_SACH" Member="SACHes" ThisKey="MaNXB" OtherKey="MaNXB" Type="SACH" />
    </Type>
  </Table>
  <Table Name="dbo.TACGIA" Member="TACGIAs">
    <Type Name="TACGIA">
      <Column Name="MaTG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTG" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Tieusu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Dienthoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TACGIA_VIETSACH" Member="VIETSACHes" ThisKey="MaTG" OtherKey="MaTG" Type="VIETSACH" />
    </Type>
  </Table>
  <Table Name="dbo.SACH" Member="SACHes">
    <Type Name="SACH">
      <Column Name="Masach" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Giaban" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Anhbia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ngaycapnhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LuotXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuotMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoiBat" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SACH_VIETSACH" Member="VIETSACHes" ThisKey="Masach" OtherKey="Masach" Type="VIETSACH" />
      <Association Name="SACH_CHITIETDONTHANG" Member="CHITIETDONTHANGs" ThisKey="Masach" OtherKey="Masach" Type="CHITIETDONTHANG" />
      <Association Name="CHUDE_SACH" Member="CHUDE" ThisKey="MaCD" OtherKey="MaCD" Type="CHUDE" IsForeignKey="true" />
      <Association Name="NHAXUATBAN_SACH" Member="NHAXUATBAN" ThisKey="MaNXB" OtherKey="MaNXB" Type="NHAXUATBAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.SP_SELECT_SACH" Method="SP_SELECT_SACH">
    <ElementType Name="SP_SELECT_SACHResult">
      <Column Name="Masach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Giaban" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Anhbia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ngaycapnhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SELECT_CHUDE" Method="SP_SELECT_CHUDE">
    <ElementType Name="SP_SELECT_CHUDEResult">
      <Column Name="MaCD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SELECT_NHAXUATBAN" Method="SP_SELECT_NHAXUATBAN">
    <ElementType Name="SP_SELECT_NHAXUATBANResult">
      <Column Name="MaNXB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenNXB" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SELECT_SACH_THEO_NXB" Method="SP_SELECT_SACH_THEO_NXB">
    <Parameter Name="MaNhaXuatBan" Parameter="maNhaXuatBan" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_SELECT_SACH_THEO_NXBResult">
      <Column Name="Masach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Giaban" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Anhbia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ngaycapnhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SELECT_SACH_THEO_CHUDE" Method="SP_SELECT_SACH_THEO_CHUDE">
    <Parameter Name="MaChuDe" Parameter="maChuDe" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_SELECT_SACH_THEO_CHUDEResult">
      <Column Name="Masach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Giaban" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Anhbia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ngaycapnhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SELECT_SACH_THEO_MASACH" Method="SP_SELECT_SACH_THEO_MASACH">
    <Parameter Name="MaSach" Parameter="maSach" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_SELECT_SACH_THEO_MASACHResult">
      <Column Name="Masach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Giaban" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Anhbia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ngaycapnhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_KIEMTRA_DANGNHAP" Method="SP_KIEMTRA_DANGNHAP">
    <Parameter Name="ID_TAIKHOAN" Parameter="iD_TAIKHOAN" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ID_MATKHAU" Parameter="iD_MATKHAU" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SP_KIEMTRA_DANGNHAPResult">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Taikhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Matkhau" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DiachiKH" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienthoaiKH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ngaysinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SELECT_USERS_THEO_EMAIL" Method="SP_SELECT_USERS_THEO_EMAIL">
    <Parameter Name="EMAIL" Parameter="eMAIL" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="SP_SELECT_USERS_THEO_EMAILResult">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_INSERT_CTDH" Method="SP_INSERT_CTDH">
    <Parameter Name="MaDonHang" Parameter="maDonHang" Type="System.Int32" DbType="Int" />
    <Parameter Name="MaSach" Parameter="maSach" Type="System.Int32" DbType="Int" />
    <Parameter Name="SoLuong" Parameter="soLuong" Type="System.Int32" DbType="Int" />
    <Parameter Name="DonGia" Parameter="donGia" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERT_DONDATHANG" Method="SP_INSERT_DONDATHANG">
    <Parameter Name="DaThanhToan" Parameter="daThanhToan" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="TinhTrangGiaoHang" Parameter="tinhTrangGiaoHang" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NgayDat" Parameter="ngayDat" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="NgayGiao" Parameter="ngayGiao" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ID_USERS" Parameter="iD_USERS" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_UPDATE_SACH_THEO_MASACH" Method="SP_UPDATE_SACH_THEO_MASACH">
    <Parameter Name="MASACH" Parameter="mASACH" Type="System.Int32" DbType="Int" />
    <Parameter Name="TENSACH" Parameter="tENSACH" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="GIABAN" Parameter="gIABAN" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="MOTA" Parameter="mOTA" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ANHBIA" Parameter="aNHBIA" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NGAYCAPNHAT" Parameter="nGAYCAPNHAT" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="SOLUONGTON" Parameter="sOLUONGTON" Type="System.Int32" DbType="Int" />
    <Parameter Name="MACD" Parameter="mACD" Type="System.Int32" DbType="Int" />
    <Parameter Name="MANXB" Parameter="mANXB" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_DELETE_SACH_THEO_MASACH" Method="SP_DELETE_SACH_THEO_MASACH">
    <Parameter Name="MASACH" Parameter="mASACH" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERT_SACH" Method="SP_INSERT_SACH">
    <Parameter Name="TENSACH" Parameter="tENSACH" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="GIABAN" Parameter="gIABAN" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="MOTA" Parameter="mOTA" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ANHBIA" Parameter="aNHBIA" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NGAYCAPNHAT" Parameter="nGAYCAPNHAT" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="SOLUONGTON" Parameter="sOLUONGTON" Type="System.Int32" DbType="Int" />
    <Parameter Name="MACD" Parameter="mACD" Type="System.Int32" DbType="Int" />
    <Parameter Name="MANXB" Parameter="mANXB" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SELECT_TACGIA" Method="SP_SELECT_TACGIA">
    <ElementType Name="SP_SELECT_TACGIAResult">
      <Column Name="MaTG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenTG" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Tieusu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Dienthoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SELECT_SACH_CUA_TACGIA" Method="SP_SELECT_SACH_CUA_TACGIA">
    <ElementType Name="SP_SELECT_SACH_CUA_TACGIAResult">
      <Column Name="TenTG" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SELECT_CHUDE_THE0_MACD" Method="SP_SELECT_CHUDE_THE0_MACD">
    <Parameter Name="MACD" Parameter="mACD" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_SELECT_CHUDE_THE0_MACDResult">
      <Column Name="MaCD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_UPDATE_CHUDE_THE0_MACD" Method="SP_UPDATE_CHUDE_THE0_MACD">
    <Parameter Name="MACD" Parameter="mACD" Type="System.Int32" DbType="Int" />
    <Parameter Name="TENCHUDE" Parameter="tENCHUDE" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_DELETE_CHUDE_THE0_MACD" Method="SP_DELETE_CHUDE_THE0_MACD">
    <Parameter Name="MACD" Parameter="mACD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERT_CHUDE" Method="SP_INSERT_CHUDE">
    <Parameter Name="TENCD" Parameter="tENCD" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SELECT_NXB_THEO_MANXB" Method="SP_SELECT_NXB_THEO_MANXB">
    <Parameter Name="MANXB" Parameter="mANXB" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_SELECT_NXB_THEO_MANXBResult">
      <Column Name="MaNXB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenNXB" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_UPDATE_NXB_THEO_MANXB" Method="SP_UPDATE_NXB_THEO_MANXB">
    <Parameter Name="MANXB" Parameter="mANXB" Type="System.Int32" DbType="Int" />
    <Parameter Name="TENNXB" Parameter="tENNXB" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="DIENTHOAI" Parameter="dIENTHOAI" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_DELETE_NXB_THEO_MANXB" Method="SP_DELETE_NXB_THEO_MANXB">
    <Parameter Name="MANXB" Parameter="mANXB" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERT_NHAXUATBAN" Method="SP_INSERT_NHAXUATBAN">
    <Parameter Name="TENNXB" Parameter="tENNXB" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="DIENTHOAI" Parameter="dIENTHOAI" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SELECT_TACGIA_THEO_MATACGIA" Method="SP_SELECT_TACGIA_THEO_MATACGIA">
    <Parameter Name="MATACGIA" Parameter="mATACGIA" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_SELECT_TACGIA_THEO_MATACGIAResult">
      <Column Name="MaTG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenTG" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Tieusu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Dienthoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_UPDATE_TACGIA_THEO_MATACGIA" Method="SP_UPDATE_TACGIA_THEO_MATACGIA">
    <Parameter Name="MATACGIA" Parameter="mATACGIA" Type="System.Int32" DbType="Int" />
    <Parameter Name="TENTACGIA" Parameter="tENTACGIA" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="TIEUSU" Parameter="tIEUSU" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DIENTHOAI" Parameter="dIENTHOAI" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_DELETE_TACGIA_THEO_MATACGIA" Method="SP_DELETE_TACGIA_THEO_MATACGIA">
    <Parameter Name="MATACGIA" Parameter="mATACGIA" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERT_TACGIA" Method="SP_INSERT_TACGIA">
    <Parameter Name="TENTACGIA" Parameter="tENTACGIA" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="TIEUSU" Parameter="tIEUSU" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DIENTHOAI" Parameter="dIENTHOAI" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERT_VIETSACH" Method="SP_INSERT_VIETSACH">
    <Parameter Name="MATACGIA" Parameter="mATACGIA" Type="System.Int32" DbType="Int" />
    <Parameter Name="MASACH" Parameter="mASACH" Type="System.Int32" DbType="Int" />
    <Parameter Name="VAITRO" Parameter="vAITRO" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="VITRI" Parameter="vITRI" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SELECT_VIETSACH_GOM_MATG_MASACH" Method="SP_SELECT_VIETSACH_GOM_MATG_MASACH">
    <ElementType Name="SP_SELECT_VIETSACH_GOM_MATG_MASACHResult">
      <Column Name="MaTG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenTG" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Masach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SELECT_VIETSACH_THEO_MATG_MASACH" Method="SP_SELECT_VIETSACH_THEO_MATG_MASACH">
    <Parameter Name="MATG" Parameter="mATG" Type="System.Int32" DbType="Int" />
    <Parameter Name="MASACH" Parameter="mASACH" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_SELECT_VIETSACH_THEO_MATG_MASACHResult">
      <Column Name="MaTG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenTG" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Masach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Vaitro" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Vitri" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_UPDATE_VIETSACH_THEO_MATG_MASACH" Method="SP_UPDATE_VIETSACH_THEO_MATG_MASACH">
    <Parameter Name="MATG" Parameter="mATG" Type="System.Int32" DbType="Int" />
    <Parameter Name="MASACH" Parameter="mASACH" Type="System.Int32" DbType="Int" />
    <Parameter Name="MATG_EDIT" Parameter="mATG_EDIT" Type="System.Int32" DbType="Int" />
    <Parameter Name="MASACH_EDIT" Parameter="mASACH_EDIT" Type="System.Int32" DbType="Int" />
    <Parameter Name="VAITRO" Parameter="vAITRO" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="VITRI" Parameter="vITRI" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_DELETE_VIETSACH_THEO_MATG_MASACH" Method="SP_DELETE_VIETSACH_THEO_MATG_MASACH">
    <Parameter Name="MATG" Parameter="mATG" Type="System.Int32" DbType="Int" />
    <Parameter Name="MASACH" Parameter="mASACH" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SELECT_SACH_TENCD_TENNXB" Method="SP_SELECT_SACH_TENCD_TENNXB">
    <ElementType Name="SP_SELECT_SACH_TENCD_TENNXBResult">
      <Column Name="Masach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Giaban" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Anhbia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ngaycapnhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenNXB" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_TIM_KIEM_SACH_THEO_TEN" Method="SP_TIM_KIEM_SACH_THEO_TEN">
    <Parameter Name="TENSACH" Parameter="tENSACH" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="SP_TIM_KIEM_SACH_THEO_TENResult">
      <Column Name="Masach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Giaban" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Anhbia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ngaycapnhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LuotXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SACH_LUOT_XEM_NHIEU" Method="SP_SACH_LUOT_XEM_NHIEU">
    <Parameter Name="SO_LUOT_XEM_YEU_CAU_THANH_SACH_LUOT_XEM_NHIEU" Parameter="sO_LUOT_XEM_YEU_CAU_THANH_SACH_LUOT_XEM_NHIEU" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_SACH_LUOT_XEM_NHIEUResult">
      <Column Name="Masach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Giaban" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Anhbia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ngaycapnhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LuotXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuotMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SACH_NOIBAT" Method="SP_SACH_NOIBAT">
    <Parameter Name="SO_LUOT_MUA_YEU_CAU_THANH_SACH_NOI_BAT" Parameter="sO_LUOT_MUA_YEU_CAU_THANH_SACH_NOI_BAT" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_SACH_NOIBATResult">
      <Column Name="Masach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Giaban" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Anhbia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ngaycapnhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LuotXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuotMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CAP_NHAT_LUOT_XEM_CUA_SACH_KHI_XEM_CHI_TIET_SACH_THEO_MA_SACH" Method="CAP_NHAT_LUOT_XEM_CUA_SACH_KHI_XEM_CHI_TIET_SACH_THEO_MA_SACH">
    <Parameter Name="MASACH" Parameter="mASACH" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CAP_NHAT_LUOT_MUA_CUA_SACH_KHI_DAT_HANG_THEO_MA_SACH" Method="CAP_NHAT_LUOT_MUA_CUA_SACH_KHI_DAT_HANG_THEO_MA_SACH">
    <Parameter Name="MASACH" Parameter="mASACH" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CAP_NHAT_SO_LUONG_TON_CUA_SACH_THEO_MA_SACH" Method="SP_CAP_NHAT_SO_LUONG_TON_CUA_SACH_THEO_MA_SACH">
    <Parameter Name="MASACH" Parameter="mASACH" Type="System.Int32" DbType="Int" />
    <Parameter Name="SOLUONGMUA" Parameter="sOLUONGMUA" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_TIM_KIEM_SACH_THEO_GIA" Method="SP_TIM_KIEM_SACH_THEO_GIA">
    <Parameter Name="GIADAU" Parameter="gIADAU" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="GIACUOI" Parameter="gIACUOI" Type="System.Decimal" DbType="Decimal(18,0)" />
    <ElementType Name="SP_TIM_KIEM_SACH_THEO_GIAResult">
      <Column Name="Masach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Giaban" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Anhbia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ngaycapnhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LuotXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuotMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SELECT_SACH_THEO_THUOC_TINH_NOI_BAT" Method="SP_SELECT_SACH_THEO_THUOC_TINH_NOI_BAT">
    <ElementType Name="SP_SELECT_SACH_THEO_THUOC_TINH_NOI_BATResult">
      <Column Name="Masach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Giaban" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Anhbia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ngaycapnhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LuotXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuotMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoiBat" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>